
# Defines the port where the config server is running so that rest of the services can pick up
# their external configurations
server:
    port: 9095
 
spring:
    cloud:
        config:
            server:
                git:
                    uri:https://github.com/Rabindra1980/microservicequickstarter/tree/microservice-config
                    # While in development mode, you can configure the config server to pick up configuration files from
# the file system
          
#           uri: file://Users/rabindra/Documents/giri/Trainings/Code Samples/Enterprise Java/Micro Services/sample-config
               searchPaths:
